version: '3.7'
services:
  gateway:
    image: nginx
    ports:
      - 8000:80
    container_name: nginx
    networks:
      - app-network
    restart: no
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    command:
      - bash
      - -c
      - 'nginx -g "daemon off;"'
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  app-network:
